### ISSUE TITLE
[scss] nested selectors not highlighting

### ISSUE THREAD

**Issue by cfsanderson** [Microsoft/vscode-css-languageservice#52] opened 2017-11-16 13:22 UTC
Nested selectors in .scss files do not seem to be highlighting correctly (see the nested `ul` in screenshot below). 
macOS Sierra 10.12.6
VSCode Version 1.18.0 (1.18.0)

![screen shot 2017-11-16 at 8 02 47 am](https://user-images.githubusercontent.com/20695956/32893283-e4622d40-caa6-11e7-9dbd-f4c4f49d07eb.png)

**Comment by aeschli** [comment] 2017-11-16 16:02
The css language service does not include syntax highlighting.
This issue needs to go to https://github.com/Microsoft/vscode.
That said, the issue is already fixed in the latest insider (1.19)

**Closed by aeschli** 2017-11-16 16:02 UTC
