### ISSUE TITLE
Add support to the css contain property

### ISSUE THREAD

**Issue by equinusocio** [Microsoft/vscode-css-languageservice#31] opened 2017-05-21 09:45 UTC
`contain` property is marked as unknown property.

**Specs:**
- https://drafts.csswg.org/css-containment/

**Other links:**
- https://developer.mozilla.org/en-US/docs/Web/CSS/contain
- https://developers.google.com/web/fundamentals/getting-started/primers/shadowdom#containment

**Comment by aeschli** [comment] 2017-05-29 14:57
duplicate of https://github.com/Microsoft/vscode/issues/10840

**Closed by aeschli** 2017-05-29 14:57 UTC
