### ISSUE TITLE
Project infrastructure: code type safety

### ISSUE THREAD

**Issue by AviVahl** [Microsoft/vscode-css-languageservice#75] opened 2018-03-11 15:05 UTC
Currently, tsconfig does not use the "strict" option, and types inside many files are way too loose.

There are also places that use `any` implicitly not caught due to this, and cases of null safety ignored by the code and tooling.

I suggest turning on strict checks and fixing the types to reflect exactly each interface.

**Comment by aeschli** [comment] 2019-03-04 10:30
duplicate of #145

**Closed by aeschli** 2019-03-04 10:30 UTC
